import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import {
  Product,
  Service,
  Promotion,
  DeliveryConfig,
  MetaAdsConfig,
  CompanyPrompts,
  CompanyLearnings,
  CompanySignals,
  PipelineConfig,
} from './company.types';

export type CompanyDocument = HydratedDocument<Company>;

@Schema({ collection: 'companies', timestamps: true })
export class Company {
  // ─── Identity ───────────────────────────────────────────────────────────────
  @Prop({ required: true, unique: true, index: true })
  tenantId: string;

  @Prop({ required: true, unique: true, index: true })
  apiKey: string;

  @Prop({ required: true })
  name: string;

  @Prop({ required: true })
  industry: string;

  // ─── Products & Services ────────────────────────────────────────────────────
  @Prop({ type: [Object], default: [] })
  products: Product[];

  @Prop({ type: [Object], default: [] })
  services: Service[];

  @Prop({ type: [Object], default: [] })
  activePromotions: Promotion[];

  // ─── Brand & Audience ───────────────────────────────────────────────────────
  @Prop({ required: true })
  targetAudience: string;

  @Prop({ type: [String], default: [] })
  audiencePersonas: string[];

  @Prop({ type: [String], default: [] })
  customerLanguage: string[];

  @Prop({ required: true })
  tone: string;

  @Prop({ type: [String], default: [] })
  avoid: string[];

  @Prop({ required: true })
  uniqueValue: string;

  @Prop({ default: '' })
  brandGuidelines: string;

  // ─── Competitive & Market ───────────────────────────────────────────────────
  @Prop({ type: [String], default: [] })
  competitors: string[];

  @Prop({ default: '' })
  competitorNotes: string;

  @Prop({ default: '' })
  calendarContext: string;

  // ─── Platforms & Geography ──────────────────────────────────────────────────
  @Prop({ type: [String], default: [] })
  platforms: string[];

  @Prop({ default: 'India' })
  geography: string;

  @Prop({ required: true })
  language: string;

  // ─── Delivery ───────────────────────────────────────────────────────────────
  @Prop({ type: Object, default: {} })
  delivery: DeliveryConfig;

  // ─── Meta Ads (per-tenant credentials) ─────────────────────────────────────
  @Prop({ type: Object, default: null })
  meta: MetaAdsConfig | null;

  // ─── Marketing Requirements ─────────────────────────────────────────────────
  @Prop({ required: true })
  weeklyBudgetCap: number;

  @Prop({ required: true })
  maxBudgetPerCampaign: number;

  @Prop({ default: 20 })
  maxBudgetScalePercent: number;

  @Prop({
    required: true,
    enum: ['conversions', 'awareness', 'traffic', 'leads'],
  })
  primaryObjective: string;

  @Prop()
  targetROAS?: number;

  @Prop()
  targetCPA?: number;

  @Prop()
  pauseIfROASBelow?: number;

  @Prop()
  pauseIfCTRBelow?: number;

  @Prop()
  pauseIfFrequencyAbove?: number;

  @Prop()
  pauseAfterDaysInLearning?: number;

  @Prop()
  scaleIfROASAbove?: number;

  @Prop({ type: [String], default: [] })
  forbiddenTopics: string[];

  @Prop({ type: [String], default: [] })
  preferredFormats: string[];

  @Prop({ default: 1 })
  campaignsPerRun: number;

  @Prop({ enum: ['weekly', 'biweekly'], default: 'weekly' })
  runFrequency: string;

  // ─── Pipeline Configuration ──────────────────────────────────────────────────
  @Prop({
    type: Object,
    default: () => ({
      mode: 'daily',
      ideasPerRun: 5,
      autoSwitch: true,
      coldStartDays: 14,
      campaignStrategy: 'balanced',
      pauseGracePeriodHours: 12,
      scaleRequiresApproval: true,
      teamMode: 'sequential',
    }),
  })
  pipelineConfig: PipelineConfig;

  // ─── Generated by Prompt Generator ─────────────────────────────────────────
  @Prop({ type: Object, default: null })
  prompts: CompanyPrompts | null;

  @Prop({ type: Object, default: null })
  learnings: CompanyLearnings | null;

  // Phase 9 — rolling performance signals from Campaign Auditor (fast feedback loop)
  @Prop({ type: Object, default: null })
  signals: CompanySignals | null;
}

export const CompanySchema = SchemaFactory.createForClass(Company);
